export enum Field {
  READ_ONE = 'read_one',
  READ_MANY = 'read_many',
  UPDATE_ONE = 'update_one',
  UPDATE_MANY = 'update_many',
  DELETE_ONE = 'delete_one',
  DELETE_MANY = 'delete_many',
  CREATE_ONE = 'create_one',
  CREATE_MANY = 'create_many',

  // 200
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  CREATE = 'create',

  // 400
  NAME = 'name',
  DESCRIPTION = 'description',
  MAT_BIEN_BAO = 'mat_bien_bao',
  MAI_BIEN_BAO = 'mai_bien_bao',
  COT_BIEN_BAO = 'cot_bien_bao',
  HOP_BIEN_BAO = 'hop_bien_bao',
  DEN_CHIEU_SANG_BIEN_BAO = 'den_chieu_sang_bien_bao',
  MONG_BIEN_BAO = 'mong_bien_bao',

  DON_VI_QUAN_LY_ID = 'don_vi_quan_ly_id',
  LOAI_NHA_CHO_ID = 'loai_nha_cho_id',
  TINH_TRANG_ID = 'tinh_trang_id',
  DIEM_DUNG_ID = 'diem_dung_id',
  LO_TRINH_DI = 'lo_trinh_di',
  LO_TRINH_VE = 'lo_trinh_ve',
  VI_TRI_ID = 'vi_tri_id',
  LOAI_DIEM_DUNG_ID = 'loai_diem_dung_id',
  DON_VI_ID = 'department_id',
  DUY_TU_ID = 'duy_tu_id',
  MAT_TRUOC = 'mat_truoc',
  MAT_SAU = 'mat_sau',
  SO_HIEU_TUYEN_BUS = 'so_hieu_tuyen_bus',
  LOAI_VACH_SON_ID = 'loai_vach_son_id',
  LOAI_PANO_ID = 'loai_pano_id',
  DUONG_ID = 'duong_id',
}
