export enum Subject {
  DISTRICT = 'district',
  DANHMUC_BIENBAO = 'danh_muc_bien_bao',
  DANHMUC_DIEMDUNG = 'danh_muc_diem_dung',

  BUS_STOP_TYPE = 'bus_stops_type',
  MAINTENNANCE_TYPE = 'maintenance_type',
  DIEM_DUNG = 'bus_stop',

  TINH_TRANG = 'tinh_trang',

  LOAI_NHA_CHO = 'loai_nha_cho',
  NHA_CHO = 'nha_cho',

  DUY_TU_DIEM_DUNG = 'bus_stop_maintenance',
  VI_TRI = 'vi_tri',
  BUS_SHELTERS = 'bus_shelter',
  VACH_SON = 'road_makings',
  LOAI_BIEN_BAO = 'traffic_sign_type',
  LOAI_VACH_SON = 'road_makings_type',
  BUS_ROUTES = 'Bus_Route',
  LOAI_DIEM_DUNG = 'bus_stop_type',
  DON_VI = 'department',
  CAY_XANH = 'trees',
  SQL_ERROR = 'sql_error',
  BUS_SHELTERS_TYPE = 'bus_shelter_type',
  FENCE = 'fence',
  INNER_SIDEWALK = 'sidewalk_bus_stop',
  BUS_STOP_BAY = 'bus_stop_bay',
  PATHWAY = 'pathway',
  TOILET = 'toilet',
  LIGHTING_SYSTEM = 'lighting_system',
  SIGNPOST = 'signpost',
  CONTROL_CENTER_HOUSE = 'control_center_house',
  ROAD = 'road',
  DUY_TU_VACH_SON = 'road_makings_maintenance',
  COMPOSITION = 'composition',
  PANO_TYPE = 'pano_type',
  PANO = 'pano',
  DUY_TU_PANO = 'pano_maintenance',
  DUY_TU_NHA_CHO = 'bus_shelter_maintenance',
}
